# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af6672ee25ebc17c9b3fcdc241f33e483d695e152a99bb7b4ef3e1c67cb6793a22d81acd37f8ae8db5d12cb093ea824b79c2e21c13d38057b320e1f44e4a4d50

test:
  secret_key_base: 3f78b3c170d1c35be08d659e840acb516e4f9cf67816bec0db3c4e75d3ed34e9e2a2325e585b828f94242007a9459d9b057cab084dd811575391418a5709dab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
